version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - './redisdata:/data'
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery worker --loglevel=info
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis